### PR TITLE
Provider an example on correlationID

### PR DESCRIPTION
**Pull request by festo**
There was no example of how to add the correlation id to each request.

### 🔧 Changes
- Extend the `EXAMPLES.md` on how to add a correlation ID to the request
### 📚 References

- https://auth0.com/docs/api/management/v2#request-correlation

### CODE REVIEW

**Comment by developerkunal** [comment]
Hi @festo ,

I hope you are doing well!

Thanks for sharing your implementation! It’s a great approach for adding headers to requests. I just wanted to let you know that the SDK already supports this via `requestOpts`. For example, you can use:  

```go
requestOpts := management.Header("X-Correlation-ID", "client1_xyz")

client := &management.Client{
	Name:        auth0.String("Test Client"),
	Description: auth0.String("This is just a test client."),
	ClientMetadata: &map[string]interface{}{
		"key1": "value1",
		"key2": "value2",
	},
}

err = api.Client.Create(context.Background(), client, requestOpts)
if err != nil {
	log.Fatalf("failed to create: %+v", err)
}
log.Printf("Client: %+v", client)
```

This will include the correlation ID in the request, and it’ll show in logs under `"references": { "correlation_id": "client1_xyz" }`.  

Let us know if you have any feedback or ideas to improve this further. Appreciate your effort! 😊

**Comment by festo** [comment]
Hi @developerkunal,

Thanks for sharing this, I was unaware of that solution, and missed this detail. I think it would be nice if one of the options would be documented because this feature is a bit hidden.

**Comment by developerkunal** [comment]
Hi @festo,

Thank you for your input! We actually have an example of using headers here: [Request Options Example](https://github.com/auth0/go-auth0/blob/main/EXAMPLES.md#request-options).

Including all header tags in the example might make it less concise and harder to follow, so we’ve aimed to keep it focused and simple. Let us know if you have any other suggestions or feedback!

**Comment by festo** [comment]
That is understandable, I should have noticed that! :) Thanks!

**Pull request closed without merging**
