### PR TITLE
[SDK-4015] Add Factor Management endpoints

### PR DESCRIPTION
**Pull request by ewanharris**
### 🔧 Changes

Adds support for the following Factor Management endpoints

Method | Endpoint | Description
-- | -- | --
GET | [/api/v2/users/{user}/authentication-methods](https://auth0.com/docs/api/management/v2#!/Users/get_authentication_methods) | Gets a list of authentication methods
GET | [/api/v2/users/{user}/authentication-methods/{authentication_method_id}](https://auth0.com/docs/api/management/v2#!/Users/get_authentication_methods_by_authentication_method_id) | Gets an authentication method by ID.
POST | [/api/v2/users/{id}/authentication-methods](https://auth0.com/docs/api/management/v2#!/Users/post_authentication_methods) | Creates an authentication method for a given user.
PUT | [/api/v2/users/{user}/authentication-methods](https://auth0.com/docs/api/management/v2#!/Users/put_authentication_methods) | Updates all authentication methods for a user by replacing them with the given ones.
PATCH | [/api/v2/users/{user}/authentication-methods/{authentication_method_id}](https://auth0.com/docs/api/management/v2#!/Users/patch_authentication_methods_by_authentication_method_id) | Updates an authentication method.
DELETE | [/api/v2/users/{user}/authentication-methods](https://auth0.com/docs/api/management/v2#!/Users/delete_authentication_methods) | Deletes all authentication methods for the given user.
DELETE | [/api/v2/users/{user}/authentication-methods/{authentication_method_id}](https://auth0.com/docs/api/management/v2#!/Users/delete_authentication_methods_by_authentication_method_id) | Deletes an authentication method by ID

### 📚 References

[SDK-4015](https://auth0team.atlassian.net/browse/SDK-4015)

### 📝 Checklist

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

[SDK-4015]: https://auth0team.atlassian.net/browse/SDK-4015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by sergiught — APPROVED** [review]
Muy bien 💯

**Comment by aishwaryamurumbekar** [comment]
Hi @ewanharris / @sergiught when can we expect this change to be released?

**Comment by ewanharris** [comment]
Hey @aishwaryamurumbekar, we're aiming to cut a new release of go-auth0 this week

**Comment by aishwaryamurumbekar** [comment]
@ewanharris thanks for updating, looking forward to it.

**Pull request merged**
