### PR TITLE
Send extra parameters with client credentials request

### PR DESCRIPTION
**Pull request by weirdian2k3**
### 🔧 Changes

The `ExtraParameters` property of `LoginWithClientCredentials` is now included in the request

### 📚 References

Issue: https://github.com/auth0/go-auth0/issues/353

### 🔬 Testing

Monitor 

```golang
		tokenSet, err := authAPI.OAuth.LoginWithClientCredentials(context.Background(), oauth.LoginWithClientCredentialsRequest{
			ClientAuthentication: oauth.ClientAuthentication{
				ClientSecret: clientSecret,
				ClientID:     "test-other-clientid",
			},
			Audience: "test-audience",
			ExtraParameters: map[string]string{
				"test": "value",
			},
		}, oauth.IDTokenValidationOptions{})
```

Watch the HTTP request to the token endpoint via your favorite network spy

Note that with the fix, `&test=value` is in the body of the client credentials request

### 📝 Checklist

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### CODE REVIEW

**Comment by weirdian2k3** [comment]
@ewanharris Hi! Sorry to bother you directly but I saw your name on other PRs. What is required next for me to get this reviewed?

**Comment by ewanharris** [comment]
@weirdian2k3 my apologies for the lack of review here, let me factor in some time next week to look at this. From a quick check it looks good but I just want to verify the support for this in other SDKs to ensure we're aligned across languages.

**Review by ewanharris — APPROVED** [review]
Thanks for the PR @weirdian2k3! I'll push the test recording separately.

**Comment by ewanharris** [comment]
Gah I thought I'd be able to merge without the test but I guess not, I made a PR to add it to your branch (seems I can't push) (https://github.com/weirdian2k3/go-auth0/pull/1), if you merge that then I should be able to merge this PR.

Otherwise I'll copy this across to another branch on Monday and then PR it with your commit + the test file commit

**Comment by weirdian2k3** [comment]
@ewanharris I'm sorry for delay getting that merged

To get through the vulnerability check, I had to update the module to use 1.21. I'm not super comfortable bumping that for you, but it seems like all the pipelines are failing until we do so.

**Comment by ewanharris** [comment]
That's fine @weirdian2k3, the support policy states that it matches the Go support cycle of last 2 majors so I we're fine to bump for the upcoming release. Thanks again for this!

**Review by ewanharris — APPROVED** [review]

**Pull request merged**
